/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author mahmoud
 */
public class MainWindow extends javax.swing.JFrame {

    public static ArrayList <Client> clients = new ArrayList <Client>();
    
    
    public MainWindow(int selectedIndex) {
        
        initComponents();
       
        if(clients.size()==0){
        Client TestClient = new Client ("Kholio Beeh Bsheeewww",1500,new Date(20,7,1997),"01113848320","Male");
        clients.add(TestClient);
        }
        clientsChoice.setModel(new DefaultComboBoxModel(clients.toArray()));
        clientsChoice.setSelectedItem(clients.get(selectedIndex));
        clientInfoTxt.setText( ((Client)clientsChoice.getSelectedItem()).Print());
        }
    
    
       

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientInfoTxt = new javax.swing.JTextPane();
        clientsChoice = new javax.swing.JComboBox<>();
        depositBtn = new javax.swing.JButton();
        withdrawBtn = new javax.swing.JButton();
        transferToBtn = new javax.swing.JButton();
        addClientBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientInfoTxt.setEditable(false);
        clientInfoTxt.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(clientInfoTxt);

        clientsChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Client 1", "Client 2", "Client 3", "Client 4" }));
        clientsChoice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clientsChoiceItemStateChanged(evt);
            }
        });
        clientsChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsChoiceActionPerformed(evt);
            }
        });

        depositBtn.setBackground(new java.awt.Color(204, 255, 204));
        depositBtn.setForeground(new java.awt.Color(0, 153, 0));
        depositBtn.setText("Deposit");
        depositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBtnActionPerformed(evt);
            }
        });

        withdrawBtn.setBackground(new java.awt.Color(255, 204, 204));
        withdrawBtn.setForeground(new java.awt.Color(255, 0, 0));
        withdrawBtn.setText("Withdraw");
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });

        transferToBtn.setBackground(new java.awt.Color(153, 255, 255));
        transferToBtn.setForeground(new java.awt.Color(51, 51, 255));
        transferToBtn.setText("Transfer to");
        transferToBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferToBtnActionPerformed(evt);
            }
        });

        addClientBtn.setBackground(new java.awt.Color(204, 255, 204));
        addClientBtn.setForeground(new java.awt.Color(0, 153, 0));
        addClientBtn.setText("Add Client");
        addClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("save");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("load");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(withdrawBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(depositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clientsChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(transferToBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addComponent(addClientBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientsChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferToBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawBtn)
                    .addComponent(depositBtn)
                    .addComponent(addClientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientsChoiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clientsChoiceItemStateChanged
        // TODO add your handling code here:
        clientInfoTxt.setText(((Client)evt.getItem()).Print());
        
    }//GEN-LAST:event_clientsChoiceItemStateChanged

    private void addClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientBtnActionPerformed

        CreateClient cc = new CreateClient(this,clients,clientsChoice.getSelectedIndex());
        cc.setLocation(this.getLocation().x+this.getWidth(),this.getLocation().y);
       
        cc.setVisible(true);

    }//GEN-LAST:event_addClientBtnActionPerformed

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
         Withdraw w = new Withdraw(this,clients,clientsChoice.getSelectedIndex());
        w.setLocation(this.getLocation().x+this.getWidth(),this.getLocation().y);
       
        w.setVisible(true);
    }//GEN-LAST:event_withdrawBtnActionPerformed

    private void depositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBtnActionPerformed
  Deposit d = new Deposit(this,clients,clientsChoice.getSelectedIndex());
        d.setLocation(this.getLocation().x+this.getWidth(),this.getLocation().y);
       
        d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_depositBtnActionPerformed

    private void transferToBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferToBtnActionPerformed
       Transfer t = new Transfer(this,clients,clientsChoice.getSelectedIndex());
        t.setLocation(this.getLocation().x+this.getWidth(),this.getLocation().y);
       
        t.setVisible(true);
    }//GEN-LAST:event_transferToBtnActionPerformed

    private void clientsChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientsChoiceActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.out.println("here svae");
        FileOutputStream fos = null;
        ObjectOutputStream oos = null;
        try {
            fos = new FileOutputStream("Accounts.data", false);
            oos = new ObjectOutputStream(fos);
            oos.writeInt(clients.size());
            for(int i = 0; i < clients.size(); i++) {
                clients.get(i).save(fos, oos);
            }
            System.out.println("saved");
        } catch(IOException ex) {
            System.out.println("Save beshew");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.out.println("here");
        FileInputStream fis = null;
        ObjectInputStream ois = null;
        try {
            fis = new FileInputStream("Accounts.data");
            ois = new ObjectInputStream(fis);
            int size = ois.readInt();
            ArrayList <Client> clients2 = new ArrayList <Client>();
            for(int i = 0; i < size; i++) {
                System.out.println("hentayeb");
                clients2.add(Client.load(fis, ois));
            }
            System.out.println("hena ba2");
            clients = clients2;
            System.out.println(clients.size());
            for(int i = 0; i < clients.size(); i++) {
                
                System.out.println(clients.get(i).getName());
            }
        } catch(IOException ex) {
            System.out.println("hena1");
            ex.printStackTrace();
        } catch(ClassNotFoundException ex) {
            System.out.println("hen2");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
   
    public static void oppaa(){
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientBtn;
    private javax.swing.JTextPane clientInfoTxt;
    private javax.swing.JComboBox<String> clientsChoice;
    private javax.swing.JButton depositBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton transferToBtn;
    private javax.swing.JButton withdrawBtn;
    // End of variables declaration//GEN-END:variables
 

}
